Fix/handle-all-security-related-issues-of-subscribe-to-plugin
weMail/Subscribe2 pull request #15
Opened 2022-12-07 21:05 UTC by MdAsifHossainNadim

2022-12-12 07:20 UTC, sapayth requested changes

2022-12-12 13:38 UTC, MdAsifHossainNadim commented on admin/settings.php
>  				$this->subscribe2_options[ $key ] = trim( $_POST[ $key ] );
Is it `wp_sanitize_key` or `sanitize_key`...???

2022-12-13 04:28 UTC, sapayth commented on admin/settings.php
>  				$this->subscribe2_options[ $key ] = trim( $_POST[ $key ] );
`sanitize_key`, sorry for the mistake

2022-12-13 05:52 UTC, Rat01047 commented
Issue-1:
Email Send is not working

Issue-2:
When a `Upload File` is chosen > Click Add More Files > The same file is already selected 

Issue-3:
When you select Add More for > Upload File - There is no way to remove the Add more option

Video for reference:
https://www.awesomescreenshot.com/video/13240279?key=8d604af8ab0b05b559737dbb9ef81ca5

2022-12-19 10:22 UTC, sapayth requested changes

2022-12-19 10:22 UTC, sapayth commented on traits/ShortcodeTrait.php
>  					$date = gmdate( 'H:i:s.u', $this->lockout );
should we use `current_datetime()` instead of `gmdate()`? please reconsider.

2022-12-19 16:26 UTC, sapayth approved these changes

2022-12-21 05:26 UTC, merged